WebClient/Models/ErrorViewModel.cs
namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebClient/Controllers/AnggotaController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class AnggotaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Pengajuan()
        {
            return View();
        }

        public IActionResult TambahPengajuan()
        {
            return View();
        }
    }
}

WebClient/Controllers/DataAnggotaController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
	public class DataAnggotaController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

WebClient/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("Login/")]
        public IActionResult Login()
        {
            return View();
        }

        [HttpGet("Unauthorized/")]
        public IActionResult Unauthorized()
        {
            return View();
        }

        [HttpGet("Forbidden/")]
        public IActionResult Forbidden()
        {
            return View();
        }

        [HttpGet("NotFound/")]
        public IActionResult NotFound()
        {
            return View();
        }
    }
}

WebClient/Controllers/JenisPinjamanController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class JenisPinjamanController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebClient/Controllers/JenisSimpananController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
	public class JenisSimpananController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

WebClient/Controllers/LaporanController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
	public class LaporanController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

WebClient/Controllers/PengajuanController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
	public class PengajuanController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

WebClient/Controllers/PenggunaController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
	public class PenggunaController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult DataUser()
		{
			return View();
		}
	}
}

WebClient/Controllers/TabunganController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
	public class TabunganController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Penarikan()
		{
			return View();
		}
	}
}

WebClient/Controllers/TransaksiController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class TransaksiController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Simpanan()
        {
            return View();
        }

        public IActionResult Pinjaman()
        {
            return View();
        }

        public IActionResult TambahSimpanan()
        {
            return View();
        }

        public IActionResult Angsuran()
        {
            return View();
        }

        public IActionResult TambahPinjaman()
        {
            return View();
        }

        public IActionResult BayarAngsuran()
        {
            return View();
        }

        public IActionResult DetailPinjaman()
        {
            return View();
        }
    }
}

WebClient/Views/Anggota/Index.cshtml
@{
	Layout = "_AnggotaLayout";
}

WebClient/Views/Anggota/Pengajuan.cshtml
@{
	Layout = "_AnggotaLayout";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
	<h1 class="h3 mb-0 text-gray-800"><i class="fas fa-fw fa-location-arrow"></i> Data Pengajuan</h1>
	<div>
	<a onclick="tambahPinjamanAnggotaPage()" class="btn btn-success mr-1"> <i class="fa fa-plus"></i> Tambah Pinjaman</a>
	<a href="../Anggota/Pengajuan" class="btn btn-secondary btn-icon-split"><span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span>
			<span class="text">Kembali</span>
	</a>
	</div>
</div>

<div class="card shadow mb-4">
	<!-- /.card-header -->
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary"><i class="fa fa-table"></i> Daftar Data Pengajuan</h6>
	</div>

	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered text-center" id="TablePengajuanAnggota" width="100%" cellspacing="0">
				<thead class="bg-primary text-white">
					<tr align="center">
						<th width="5%">No</th>
						<th>Kode Pengajuan</th>
						<th>Tanggal Pengajuan</th>
						<th>Besar Pinjaman</th>
						<th>Status</th>
						<th>Tanggal Terima</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
			</table>
		</div>
	</div>
</div>

WebClient/Views/Anggota/TambahPengajuan.cshtml
@{
	Layout = "_AnggotaLayout";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
	<h1 class="h3 mb-0 text-gray-800"><i class="fas fa-fw fa-dolly-flatbed"></i> Data Transaksi</h1>

	<a onclick="backPinjamanAnggotaPage()" class="btn btn-secondary btn-icon-split"><span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span>
		<span class="text">Kembali</span>
	</a>
</div>

<div class="card shadow mb-4">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary"><i class="fas fa-fw fa-plus"></i> Tambah Data Pinjaman</h6>
	</div>
		<div class="card-body">
			<div class="row">
				<div class="form-group col-md-6">
					<label class="font-weight-bold">Kode Anggota</label>
					<input autocomplete="off" type="text" name="kode_anggota" value="" required class="form-control" readonly="readonly"/>
				</div>

				<div class="form-group col-md-6">
					<label class="font-weight-bold">Nama Anggota</label>
					<input autocomplete="off" type="text" name="nama_anggota" value="" required class="form-control" readonly="readonly"/>
				</div>

				<div class="form-group col-md-6">
					<label class="font-weight-bold">Pekerjaan</label>
					<input autocomplete="off" type="text" name="pekerjaan" value="" required class="form-control" readonly="readonly"/>
				</div>

				<div class="form-group col-md-6">
					<label class="font-weight-bold">Jenis Pinjaman</label>
					<select name="kode_jenis_pimpan" id="id_jenis_pinjaman" onChange="" class="form-control" required>		  
					</select>
				</div>

				<div class="form-group col-md-6">
					<label class="font-weight-bold">Lama Angsuran (Bulan)</label>
					<input autocomplete="off" type="number" name="lama_angsuran" value="" required readonly class="form-control"/>
				</div>

				<div class="form-group col-md-6">
					<label class="font-weight-bold">Maksimum Peminjaman</label>
					<input autocomplete="off" type="text" name="maks_pinjam" value="" required class="form-control" readonly="readonly"/>
				</div>

				<div class="form-group col-md-6">
					<label class="font-weight-bold">Bunga(%)</label>
					<input autocomplete="off" type="number" name="besar_bunga" value="" required class="form-control" readonly="readonly"/>
				</div>

				<div class="form-group col-md-6">
					<label class="font-weight-bold">Besar Pinjaman</label>
					<input autocomplete="off" type="number" name="besar_pinjaman" value="" required class="form-control"/>
				</div>

				<div class="form-group col-md-6">
					<label class="font-weight-bold">Besar Angsuran</label>
					<input autocomplete="off" type="text" name="besar_angsuran" value="" required class="form-control" readonly="readonly"/>
				</div>

				<div class="form-group col-md-6">
					<label class="font-weight-bold">User Entri</label>
					<input autocomplete="off" type="text" name="tgl_entri" value="Admin" required class="form-control" readonly="readonly"/>
				</div>
				<div class="form-group col-md-6">
					<label class="font-weight-bold">Tanggal Entri</label>
					<input autocomplete="off" type="text" name="tgl_entri" value="@DateTime.Now.ToString("MM/dd/yyyy")" required class="form-control" readonly="readonly"/>
				</div>
			</div>

		</div>
		<div class="card-footer text-right">
			<button onclick="tambahPengajuanAnggotaPage()" class="btn btn-success"><i class="fa fa-save"></i> Simpan</button>
			<button type="reset" class="btn btn-info"><i class="fa fa-sync-alt"></i> Reset</button>
		</div>
</div>

WebClient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_AdminLayout";
}

WebClient/Views/Home/Login.cshtml
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<meta name="description" content="" />
		<meta name="author" content="" />

		<title>Aplikasi Manajemen Pengelolaan Simpan Pinjam</title>

 <!-- Custom fonts for this template-->
	<link href="~/lib/Sbadmin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
	<!-- Custom styles for this template-->
	<link href="~/lib/Sbadmin/css/sb-admin-2.min.css" rel="stylesheet">
	<!-- Datatables-->
	<link href="~/lib/Sbadmin/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
	</head>

	<body class="bg-gradient-primary">
		<div class="container py-5">
			<!-- Outer Row -->
			<div class="row justify-content-center">
				<div class="col-xl-5 col-lg-5 col-md-9">
					<div style="margin-bottom: 30px;">
						<div class="text-white text-center font-weight-bold" style="font-size: 60px;">
						  <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-bank" viewBox="0 0 16 16">
						  <path d="m8 0 6.61 3h.89a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5H15v7a.5.5 0 0 1 .485.38l.5 2a.498.498 0 0 1-.485.62H.5a.498.498 0 0 1-.485-.62l.5-2A.501.501 0 0 1 1 13V6H.5a.5.5 0 0 1-.5-.5v-2A.5.5 0 0 1 .5 3h.89L8 0ZM3.777 3h8.447L8 1 3.777 3ZM2 6v7h1V6H2Zm2 0v7h2.5V6H4Zm3.5 0v7h1V6h-1Zm2 0v7H12V6H9.5ZM13 6v7h1V6h-1Zm2-1V4H1v1h14Zm-.39 9H1.39l-.25 1h13.72l-.25-1Z"/>
						</svg>
						</div>
						<h3 class="text-white text-center font-weight-bold">Aplikasi Manajemen Pengelolaan Simpan Pinjam</h3>
					</div>

					<div class="card text-center">
					  <div class="card-body">
						<div class="text-center">
							<h1 class="h4 text-gray-900 mb-3">Login</h1>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<div class="p-3">
										<div class="form-group">
											<input type="text" class="form-control form-control-user" id="usernameLogin" placeholder="User Name" autocomplete="off" required />
										</div>
										<div class="form-group">
											<input type="password" class="form-control form-control-user" id="passwordLogin" placeholder="Password" autocomplete="off" required />
										</div>
										<button onclick="login()" class="btn btn-primary btn-user btn-block"><i class="fas fa-fw fa-sign-in-alt mr-1"></i> Masuk</button>
								</div>
							</div>
						</div>
					  </div>
					</div>
				</div>
			</div>
		</div>

		<!-- Bootstrap core JavaScript-->
		<script src="~/lib/Sbadmin/vendor/jquery/jquery.min.js"></script>
		<script src="~/lib/Sbadmin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

		<!-- Core plugin JavaScript-->
		<script src="~/lib/Sbadmin/vendor/jquery-easing/jquery.easing.min.js"></script>

		<!-- Custom scripts for all pages-->
		<script src="~/lib/Sbadmin/js/sb-admin-2.min.js"></script>
		<script src="~/js/Account/Login.js"></script>
	</body>
</html>

WebClient/Views/Home/NotFound.cshtml
@{
    Layout = "_AdminLayout";
}


<div class="container-fluid">

    <!-- 404 Error Text -->
    <div class="text-center">
        <div class="error mx-auto" data-text="404">404</div>
        <p class="lead text-gray-800 mb-5">Page Not Found</p>
        <p class="text-gray-500 mb-0">It looks like you found a glitch in the matrix...</p>
        <a href="../">&larr; Back to Dashboard</a>
    </div>

</div>

WebClient/Views/Laporan/Index.cshtml
@{
	Layout = "_AdminLayout";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
	<h1 class="h3 mb-0 text-gray-800"><i class="fas fa-fw fa-users"></i> Data Anggota</h1>

</div>

<div class="card shadow mb-4">
	<!-- /.card-header -->
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary"><i class="fa fa-table"></i> Daftar Data Anggota</h6>
	</div>

	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered text-center" id="TableLaporanAnggota" width="100%" cellspacing="0">
				<thead class="bg-primary text-white">
					<tr align="center">
						<th width="5%">No</th>
						<th>Kode Anggota</th>
						<th>Nama Anggota</th>
						<th>Tanggal Lahir</th>
						<th>Alamat</th>
						<th>Email</th>
						<th>Jenis Kelamin</th>
						<th>Pekerjaan</th>
						<th>Tanggal Masuk</th>
						<th>Status</th>
						<th>Telepon</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
			</table>
		</div>
	</div>
</div>

WebClient/Views/Pengguna/DataUser.cshtml
@{
	Layout = "_AdminLayout";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
	<h1 class="h3 mb-0 text-gray-800"><i class="fas fa-fw fa-users"></i> Data Pengguna</h1>

	<a asp-controller="Pengguna" asp-action="Index" class="btn btn-secondary btn-icon-split">
		<span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span>
		<span class="text"> Kembali</span>
	</a>
</div>

<div class="card shadow mb-4">
	<!-- /.card-header -->
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary"><i class="fa fa-table"></i> Tambah Data Pengguna</h6>
	</div>

	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered text-center" id="TableDataUser" width="100%" cellspacing="0">
				<thead class="bg-primary text-white">
					<tr align="center">
						<th width="5%">No</th>
						<th>Nomor Anggota</th>
						<th>Username</th>
						<th>Nama</th>>
						<th>Status</th>
						<th>Aksi</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
			</table>
		</div>
	</div>
</div>

WebClient/Views/Shared/_AnggotaLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Page Anggota</title>

    <!-- Custom fonts for this template-->
    <link href="~/lib/Sbadmin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/lib/Sbadmin/css/sb-admin-2.min.css" rel="stylesheet">
    <!-- Datatables-->
    <link href="~/lib/Sbadmin/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/jszip-2.5.0/dt-1.13.1/b-2.3.3/b-colvis-2.3.3/b-html5-2.3.3/datatables.min.css" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center">
                <div class="sidebar-brand-icon">
                    <i class="fas fa-hand-holding-usd"></i>
                </div>
                <div class="sidebar-brand-text mx-3">APPS KOPERASI</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Anggota" asp-action="Index">
                    <i class="fas fa-fw fa-home"></i>
                    <span>Dashboard</span>
                </a>
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                MASTER DATA
            </div>

            <li class="nav-item">
                <a class="nav-link" asp-controller="Anggota" asp-action="Pengajuan">
                    <i class="fas fa-fw fa-location-arrow"></i>
                    <span>Data Pengajuan</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                MASTER SETTING
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i class="fas fa-fw fa-cogs"></i>
                    <span>Data Profile</span>
                </a>
            </li>

              <!-- Divider -->
              <hr class="sidebar-divider d-none d-md-block">

              <!-- Sidebar Toggler (Sidebar) -->
              <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
              </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span id="namaAkun1" class="mr-2 d-none d-lg-inline text-gray-600 small">Anggota</span>
                                <img class="img-profile rounded-circle"
                                     src="~/lib/Sbadmin/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Keluar
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        © <script>
                                  document.write(new Date().getFullYear())
                            </script>,
                            made with <i class="fa fa-heart" style='color: red'></i> by
                            <a href="#" class="font-weight-bold">MCC Batch #71 Kelompok 3</a>
                            for a better web.
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Yakin ingin keluar?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Pilih "Keluar" untuk mengakhiri sesi masuk ini.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Batal</button>
                    <a onclick="logoutAccount()" class="btn btn-primary">Keluar</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/Sbadmin/vendor/jquery/jquery.min.js"></script>
    <script src="~/lib/Sbadmin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/lib/Sbadmin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/lib/Sbadmin/js/sb-admin-2.min.js"></script>

    <!-- Datatables -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/jszip-2.5.0/dt-1.13.1/b-2.3.3/b-colvis-2.3.3/b-html5-2.3.3/datatables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
    <script src="~/lib/Sbadmin/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="/lib/Sbadmin/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
    <script src="//cdn.datatables.net/plug-ins/1.10.11/sorting/datetime-moment.js"></script>
    <script src="//cdn.datatables.net/plug-ins/1.13.1/dataRender/datetime.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="~/js/Anggota/PengajuanAnggota.js"></script>
     <script src="~/js/Anggota/TambahPinjaman.js"></script>
     <script src="~/js/Account/Logout.js"></script>


</body>

</html>

WebClient/Views/Tabungan/Penarikan.cshtml
@{
	Layout = "_AdminLayout";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
	<h1 class="h3 mb-0 text-gray-800"><i class="fas fa-fw fa-money-bill-wave"></i> Data Tabungan</h1>

	<a asp-controller="Tabungan" asp-action="Index" class="btn btn-secondary btn-icon-split">
		<span class="icon text-white-50"><i class="fas fa-arrow-left"></i></span>
		<span class="text">Kembali</span>
	</a>
	@*<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModal"> <i class="fa fa-plus"></i> Tambah Data </button>*@
</div>

<div class="card shadow mb-4">
	<!-- /.card-header -->
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary"><i class="fa fa-table"></i> Data Penarikan Uang <span id="namaAnggotaPenarikan"></span></h6>
	</div>
	<div class="card-body">
			<div class="row">
				<div class="form-group col-md-4">
					<label class="font-weight-bold">Total Saldo</label>
					<input autocomplete="off" type="text" id="txt1" onkeyup="sum();" name="saldo" value="" required class="form-control" readonly="readonly"/>
				</div>
  
				<div class="form-group col-md-4">
					<label class="font-weight-bold">Besar Ambil Uang</label>
					<input autocomplete="off" type="text" id="txt2" onkeyup="sum();" onkeypress="return isNumberKey(event)" name="besar_ambil" required class="form-control" />
				</div>
				
				<div class="form-group col-md-4">
					<label class="font-weight-bold">Sisa Uang</label>
					<input autocomplete="off" type="text" id="txt3" onkeyup="sum();" onkeypress="return isNumberKey(event)" required class="form-control" readonly="readonly"/>
				</div>
			</div>
		<div class="card-footer text-right">
            <button onclick="penarikanUang()" class="btn btn-primary"><i class="fa fa-check"></i> Tarik Uang</button>
            <button type="reset" class="btn btn-info"><i class="fa fa-sync-alt"></i> Reset</button>
        </div>
	</div>
</div>

<div class="card shadow mb-4">
	<!-- /.card-header -->
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary"><i class="fa fa-table"></i> Data Riwayat Penarikan Uang <span id="namaAnggotaRiwayatPenarikan"></span></h6>
	</div>

	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered text-center" id="TablePenarikan" width="100%" cellspacing="0">
				<thead class="bg-primary text-white">
					<tr align="center">
						<th width="5%">No</th>
						<th>Kode Penarikan</th>
						<th>Kode Tabungan</th>
						<th>Besar Penarikan</th>
						<th>Tanggal Ambil</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
			</table>
		</div>
	</div>
</div>